# .github/workflows/update-readme.yml
name: Update README

on: [push]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Generate README
        run: |
          cat Usage.md > README.md
          for img in $(find ./wallpapers -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.webp" \) | sort); do
            img="${img#./}"
            name="${img%.*}"
            echo "### $name" >> README.md
            echo "![${name}](${img})" >> README.md
            echo "" >> README.md
          done
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update README.md showcase"
